name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Setup Git
        run: |
          git config --global user.email ${{ secrets.RELEASE_USER_EMAIL }}
          git config --global user.name ${{ secrets.RELEASE_USER }}

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          createGithubReleases: true
          setupGitUser: false
          commit: 'chore: update versions'
          title: 'chore: update versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
